"""add is_deleted field

Revision ID: 08d7a415bb29
Revises: 7984e8485056
Create Date: 2023-03-14 07:57:30.493501

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08d7a415bb29'
down_revision = '7984e8485056'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
