"""add users deleted_at field

Revision ID: 73f96ee4c2bd
Revises: fac842dae425
Create Date: 2023-03-10 08:10:03.631080

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73f96ee4c2bd'
down_revision = 'fac842dae425'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.create_unique_constraint(None, 'users', ['username'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'deleted_at')
    # ### end Alembic commands ###
