version: "3"


services:
  db_users:
    container_name: db_fastapi_users
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fastapi_users_test
      PGDATA: /data/postgresc
    volumes:
      - postgres_users:/data/postgres
    ports:
      - "5432:5432"
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

  db_videos:
    container_name: db_fastapi_videos
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fastapi_videos_test
      PGDATA: /data/postgresc
    volumes:
      - postgres_videos:/data/postgres
    ports:
      - "5433:5432"
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

  user_service:
    build:
      context: .
      dockerfile: user_service/Dockerfile
    ports:
      - "5000:5000"
    env_file:
      - ./user_service/.env.test
    volumes:
      - ./user_service:/app
      - ./shared:/app/shared
    depends_on:
      db_users:
        condition: service_healthy

  video_service:
    build:
      context: .
      dockerfile: video_service/Dockerfile
    ports:
      - "5100:5100"
    env_file:
      - ./video_service/.env.test
    volumes:
      - ./video_service:/app
      - ./shared:/app/shared
    depends_on:
      db_videos:
        condition: service_healthy

volumes:
  postgres_users:

  postgres_videos:
