version: "3"


services:
  db:
    container_name: db_videoplatform
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: videoplatform
      PGDATA: /data/postgresc
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    restart: always

  mongo:
    container_name: mongodb
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
      - MONGO_INITDB_DATABASE=video_statistics
    ports:
      - "27017:27017"

  rabbitmq:
    container_name: rabbitmq
    image: public.ecr.aws/docker/library/rabbitmq:3
    ports:
      - "5672:5672"
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 15s
      timeout: 15s
      retries: 10

  user_service:
    build:
      context: .
      dockerfile: user_service/Dockerfile
    ports:
      - "5000:5000"
    entrypoint: /user_service_entrypoint.sh
    volumes:
      - ./user_service:/app/user_service
    depends_on:
      db:
        condition: service_started

  video_service:
    build:
      context: .
      dockerfile: video_service/Dockerfile
    ports:
      - "5100:5100"
    entrypoint: /video_service_entrypoint.sh
    volumes:
      - ./video_service:/app/video_service
    depends_on:
      db:
        condition: service_started

  statistics_service:
    build:
      context: .
      dockerfile: statistics_service/Dockerfile
    ports:
      - "5200:5200"
    entrypoint: /statistics_service_entrypoint.sh
    volumes:
      - ./statistics_service:/app/statistics_service
    depends_on:
      mongo:
        condition: service_started

  celery:
    container_name: celery
    build:
      context: .
      dockerfile: statistics_service/Dockerfile
    entrypoint: /celery_entrypoint.sh
    depends_on:
      statistics_service:
        condition: service_started
      rabbitmq:
        condition: service_healthy


volumes:
  postgres: